### ISSUE TITLE
Given an embedding list, how to perform ssr on it?

### ISSUE THREAD

**Issue by algoteam5** [XiSHEN0220/SSR#1]
Given an embedding list, how to perform SSR on it? An embedding list includes a list of images that are encoded into embeddings using a neural network.

**Comment by XiSHEN0220** [comment]
Hi, thanks for your interest! 

For simplicity, let me take the retrieval on Oxford to explain the workflow: 

1. given a query, compute the similarities to all the samples in the database: https://github.com/XiSHEN0220/SSR/blob/main/image_retrieval/test_ssr_QE.py#L126

2. the similarities provide an initial rank: https://github.com/XiSHEN0220/SSR/blob/main/image_retrieval/test_ssr_QE.py#L127

3. SSR takes the query and the top retrieved samples as inputs https://github.com/XiSHEN0220/SSR/blob/main/image_retrieval/test_ssr_QE.py#L133-L139

4. The outputs of SSR is a refined score which can be used to re-rank the top retrieved samples: https://github.com/XiSHEN0220/SSR/blob/main/image_retrieval/test_ssr_QE.py#L141-L142

Note that SSR has its learnable parameters and needs a training set.  

Hope it helps! 

Best, 

Xi

**Comment by algoteam5** [comment]
Interesting! Thanks for specifying the flow. How would I train another `net_ssr` using a different dataset? I can see `gl18_resnet101_sfm120k` having 2 attributes `database` and `cluster`. What are they and how can I construct a similar one using a different dataset? @XiSHEN0220 @hushell

**Comment by XiSHEN0220** [comment]
`database` is a pool of features that one aims to conduct retrieval. 
`cluster` is the category annotations of the database features.
