### ISSUE TITLE
Asking about the dataset

### ISSUE THREAD

**Issue by algoteam5** [XiSHEN0220/SSR#2]
What do you mean by "database", "query", and "gt"?

```
    ### Oxford
    oxford_db = info_oxford['database'].T
    oxford_query = info_oxford['query'].T
    oxford_gt = info_oxford['gt']

```

**Comment by XiSHEN0220** [comment]
For image **Q**, we aim at retrieving images in set **D**, which are similar to **Q**. 

**Q**,  is the "query". 
**D**  is the "database"

"gt" means the ground-truth ones.
